### ISSUE TITLE
Add mohawk2 as a core dev

### ISSUE THREAD

**Issue by jberger** [Perl5-Alien/Perl5-Alien-Documents#3]
Another willing volunteer has emerged. This will also be up for a vote with the initial 3 members. @mohawk2 has contributed to EUMM and EU::Depends and driven PR completion in those projects.

**Comment by mohawk2** [comment]
@jberger has been kind enough to propose me, and invited me to make a brief statement.

I am interested in seeing A::B be responsive to user concerns like issues and PRs. I don't particularly have an agenda otherwise, and on matters of policy going forward I am keen to have a consensus.

**Comment by MidLifeXis** [comment]
Moving discussion on the voting process to #4.

**Comment by jberger** [comment]
I am adding @mohawk2 to the core team, however, I want to make one public statement of emphasis, @mohawk2 seems to be both eager (good) and a little aggressive in getting things done (not always good). Please lets all just do what is good for the project and what is good for the community.
